### ISSUE TITLE
Move 2024 Enum support - estimates on complexity

### ISSUE THREAD

**Issue by fl0ydj** [kunalabs-io/sui-client-gen#11]
Hey @kklas,
first thing: I really love sui-client-gen and it helps us soo much. Honestly!

Enums would be really helpful for our project and hence we are considering whether we should design our architecture around them.
While they are not even out yet, have you thought about the complexities of supporting them yet and how long it would take you to add support for them to sui-client-gen? I could imagine with the reified concept it shouldn't be too hard?

Just asking this early, as this will also help us decide whether or not to rely on enums for our architecture.

**Comment by kklas** [comment]
Hey @fl0ydj, thanks, I appreciate that!

In terms of complexity, I think that fundamentally there isn't anything that would obstruct the implementation of this or make it more complex than it should be. You would probably generate a separate "enum class" for each invariant and then define a union type with all of them. A separate `EnumClassReified` interface would have to be added and supported throughout `reified.ts`. So it's a bit of work but my gut feeling is it should be reasonably straightforward. The reified stuff is quite esoteric so you can never be 100% sure though until you try to do it.

In any case, support for enums will definitely be added because they're a core part of Move, and the generator will work with Move 2024. It's just a matter of how good it will be. I can't be 100% certain but I'd give it a very good chance that they'll work as well as any other types.

**Comment by fl0ydj** [comment]
Thanks for the quick response.
That sounds great!

Closing this accordingly :)
